import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";
import Navbar from "@/components/ui/Navbar";
import { Button, Col, Row } from "antd";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Career Consultation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Row justify="space-between" align="middle">
            <Col span={18}>
              <Link style={{ margin: 10 }} href="/">
                <Button type="text" style={{}}>
                  Career Consultation
                </Button>
              </Link>
            </Col>
            <Col span={6}>
              <Navbar />
            </Col>
          </Row>
          {children}
        </Providers>
      </body>
    </html>
  );
}
