import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";
import Navbar from "@/components/ui/Navbar";
import { Button, Col, Row } from "antd";
import Link from "next/link";
import { Footer } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Career Consultation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Row justify="space-between" align="middle">
            <Col span={12}>
              <Button type="text" size="large" content="Hello">
                <Link
                  style={{
                    fontWeight: "bold",
                  }}
                  href="/"
                >
                  Career Consultation
                </Link>
              </Button>
            </Col>
            <Col span={12}>
              <Row justify="start">
                <Navbar />
              </Row>
            </Col>
          </Row>
          {children}
          <Footer style={{ textAlign: "center" }}>
            <p>&copy; 2023 Career Consultation. All rights reserved.</p>
          </Footer>
        </Providers>
      </body>
    </html>
  );
}
